name: emart_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"   # ðŸ”´ IMPORTANT (voir explication plus bas)

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
 

  cupertino_icons: ^1.0.6
  velocity_x:
  google_fonts: ^6.3.3
  responsive_sizer: ^3.3.1
  page_transition: ^2.2.1
  url_launcher: ^6.1.7
  badges: ^3.1.1
  uuid:  ^4.0.0
  
  # ðŸ”¥ FIREBASE (ICI ET PAS AILLEURS)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  sign_in_with_apple: ^4.2.0
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  animated_bottom_navigation_bar: ^1.4.0
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
